batch: 16
conf: 0.25
data: datasets/INRIAPerson/runtime_inria.yaml
deterministics: true
epochs: 100
imgsz: 640
init_path: !!python/object/apply:pathlib._local.PosixPath
- exps/advyolo_oldupper/worst.pt
lr: 0.02
method: gd
objective: obj
patch_blur: true
patch_random_rotate: true
pretrained_weight: pretrained/yolov8n.pt
prob_supervised: true
psize: 300
ptype: random
seed: 891122
