batch: 16
conf: 0.25
data: datasets/INRIAPerson/runtime_inria.yaml
deterministics: true
epochs: 50
imgsz: 512
logit_to_prob: false
lr: 0.03
method: gd
patch_blur: true
patch_random_rotate: true
pretrained_weight: pretrained/yolov8n.pt
prob_supervised: false
psize: 300
ptype: random
seed: 891122
