batch: 16
conf: 0.25
data: datasets/INRIAPerson/runtime_inria.yaml
deterministics: true
epochs: 10
imgsz: 640
lr: 0.01
method: gd
objective: cls-obj
patch_blur: true
patch_random_rotate: true
pretrained_weight: pretrained/yolov8n.pt
prob_supervised: true
psize: 300
ptype: random
seed: 891122
