batch: 16
data: INRIAPerson/inria.yaml
det_loss_scale: false
deterministics: true
epochs: 50
lr: 0.01
method: gd
patch_blur: true
patch_random_rotate: true
pretrained_weight: pretrained/yolov8n.pt
psize: 300
ptype: gray
seed: 891122
